name: 'Documentation'
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  BTD:
    runs-on: ubuntu-latest
    name: 'sample'

    steps:

    - uses: actions/checkout@v2

    - run: pwd
      shell: bash

    - run: ls
      shell: bash

    - name: '🚀 Deploy'
      uses: TerosTechnology/teroshdl-documenter-action@0.0.7
  